# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DockerMachineSakuracloud < Formula
  desc ""
  homepage "https://github.com/sacloud/docker-machine-sakuracloud"
  version "1.6.0"
  license "Apache 2.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sacloud/docker-machine-sakuracloud/releases/download/v1.6.0/docker-machine-driver-sakuracloud_1.6.0_darwin_amd64.zip"
      sha256 "ea537a43e15885113189638e3a2be50c783dbc7f161585f14485e009718f5808"
    end
    if Hardware::CPU.arm?
      url "https://github.com/sacloud/docker-machine-sakuracloud/releases/download/v1.6.0/docker-machine-driver-sakuracloud_1.6.0_darwin_arm64.zip"
      sha256 "428ccecf30294cdb0e1ef22870365fdb2761896814aa73c5070f1ba562610e4b"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/sacloud/docker-machine-sakuracloud/releases/download/v1.6.0/docker-machine-driver-sakuracloud_1.6.0_linux_arm.zip"
      sha256 "ec4a4fd952b59fc7da8c3b7d97b0dcc8b487d520965e327ea855c8ec1190938a"
    end
    if Hardware::CPU.intel?
      url "https://github.com/sacloud/docker-machine-sakuracloud/releases/download/v1.6.0/docker-machine-driver-sakuracloud_1.6.0_linux_amd64.zip"
      sha256 "610f028b47dbd5d484863f8e8789f7573a992d6b7e5421a243c76857aabefc89"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sacloud/docker-machine-sakuracloud/releases/download/v1.6.0/docker-machine-driver-sakuracloud_1.6.0_linux_arm64.zip"
      sha256 "bc44b36f17c4fef636807eea1697625f30d11a6b8ddece80f7df25b6a8bf05e6"
    end
  end

  def install
    bin.install "docker-machine-sakuracloud"
  end

  test do
    system "#{bin}/docker-machine-driver-sakuracloud --version"
  end
end
